# Generated by Django 3.0.4 on 2020-03-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('closed', 'closed'), ('opened', 'opened'), ('in_progress', 'in_progress')], default='opened', max_length=20)),
            ],
        ),
    ]
